# default attributes
default['rb-arubacentral']['registered'] = false
default['redborder']['rb-arubacentral']['logdir'] = '/var/log/rb-arubacentral'
default['redborder']['rb-arubacentral']['configdir'] = '/etc/rb-arubacentral'
default['redborder']['rb-arubacentral']['user'] = 'rb-arubacentral'
default['redborder']['rb-arubacentral']['group'] = 'rb-arubacentral'
default['redborder']['rb-arubacentral']['arubacentral_nodes'] = []
default['redborder']['rb-arubacentral']['flow_nodes'] = []
default['redborder']['rb-arubacentral']['kafka_brokers'] = ['kafka.service']
